In [3]:
import numpy as np
import cv2


def labeling_basic():
    src = np.array([[0, 0, 1, 1, 0, 0, 0, 0],
                    [1, 1, 1, 1, 0, 0, 1, 0],
                    [1, 1, 1, 1, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 1, 1, 0],
                    [0, 0, 0, 1, 1, 1, 1, 0],
                    [0, 0, 0, 1, 0, 0, 1, 0],
                    [0, 0, 1, 1, 1, 1, 1, 0],
                    [0, 0, 0, 0, 0, 0, 0, 0]]).astype(np.uint8)

    # 0,1,2,3,4 바꾸기 위해서 (8비트)
    # 2진화를 위해서, 극명하게 구분 시킨다.
    # 코드에서 src = src * 255를 사용하는 이유는 
    # 이진 이미지의 값을 8비트 그레이스케일 이미지의 값으로 변환하기 위함입니다.
    # 이진 이미지 표현: 
    #   초기 src 배열은 값이 0과 1인 이진 이미지를 나타냅니다.
    # 그레이스케일 변환: 
    #   8비트 그레이스케일 이미지에서는 픽셀 값이 0에서 255까지 범위입니다. 여기서 0은 검정색, 255는 흰색을 나타냅니다.
    
    
    # 이진 이미지의 값에 255를 곱하면:
    # 0은 그대로 0 (검정색)
    # 1은 255로 변환됩니다 (흰색)
    src = src * 255    

    cnt, labels = cv2.connectedComponents(src)

    print('src:'), 
    print(src)
    print('labels:')
    print(labels)
    print('number of labels:', cnt)


def labeling_stats():
    src = cv2.imread('../../data/img/bbb.png', cv2.IMREAD_GRAYSCALE)

    if src is None:
        print('Image load failed!')
        return

    # 엣지 검출과 같이 쓴다. 바이너리, 오츠
    _, src_bin = cv2.threshold(src, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)

    cnt, labels, stats, centroids = cv2.connectedComponentsWithStats(src_bin)

    dst = cv2.cvtColor(src, cv2.COLOR_GRAY2BGR)

    for i in range(1, cnt):
        (x, y, w, h, area) = stats[i]

        if area < 20:
            continue

        pt1 = (x, y)
        pt2 = (x + w, y + h)
        cv2.rectangle(dst, pt1, pt2, (0, 255, 255))

    # cv2.imshow('src', src)
    cv2.imshow('dst', dst)

    cv2.waitKey()
    cv2.destroyAllWindows()


if __name__ == "__main__":
    #labeling_basic()
    labeling_stats()


In [2]:
def sobel_edge():
    src = cv2.imread('../data/img/coins.jpg', cv2.IMREAD_GRAYSCALE)

    if src is None:
        print('Image load failed!')
        return

    dx = cv2.Sobel(src, cv2.CV_32F, 1, 0)
    dy = cv2.Sobel(src, cv2.CV_32F, 0, 1)

    fmag = cv2.magnitude(dx, dy)
    mag = np.uint8(np.clip(fmag, 0, 255))
    _, edge = cv2.threshold(mag, 150, 255, cv2.THRESH_BINARY)

    # cv2.imshow('src', src)
    # cv2.imshow('mag', mag)
    # cv2.imshow('edge', edge)
    cv2.imwrite('../data/img/coins.png', mag)
    cv2.waitKey()
    cv2.destroyAllWindows()
sobel_edge()

Image load failed!


In [4]:
import numpy as np
import cv2



def sobel_edge():
    src = cv2.imread('../data/img/bbb.png', cv2.IMREAD_GRAYSCALE)

    if src is None:
        print('Image load failed!')
        return

    dx = cv2.Sobel(src, cv2.CV_32F, 1, 0)
    dy = cv2.Sobel(src, cv2.CV_32F, 0, 1)

    fmag = cv2.magnitude(dx, dy)
    mag = np.uint8(np.clip(fmag, 0, 255))
    _, edge = cv2.threshold(mag, 150, 255, cv2.THRESH_BINARY)

    # Save the result to a file
    cv2.imwrite('../data/img/result.png', mag)
    cv2.imshow('mag', mag)
    cv2.waitKey()
    cv2.destroyAllWindows()


def labeling_basic():
    src = np.array([[0, 0, 1, 1, 0, 0, 0, 0],
                    [1, 1, 1, 1, 0, 0, 1, 0],
                    [1, 1, 1, 1, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 1, 1, 0],
                    [0, 0, 0, 1, 1, 1, 1, 0],
                    [0, 0, 0, 1, 0, 0, 1, 0],
                    [0, 0, 1, 1, 1, 1, 1, 0],
                    [0, 0, 0, 0, 0, 0, 0, 0]]).astype(np.uint8)

    # 0,1,2,3,4 바꾸기 위해서 (8비트)
    # 2진화를 위해서, 극명하게 구분 시킨다.
    # 코드에서 src = src * 255를 사용하는 이유는 
    # 이진 이미지의 값을 8비트 그레이스케일 이미지의 값으로 변환하기 위함입니다.
    # 이진 이미지 표현: 
    #   초기 src 배열은 값이 0과 1인 이진 이미지를 나타냅니다.
    # 그레이스케일 변환: 
    #   8비트 그레이스케일 이미지에서는 픽셀 값이 0에서 255까지 범위입니다. 여기서 0은 검정색, 255는 흰색을 나타냅니다.
    
    
    # 이진 이미지의 값에 255를 곱하면:
    # 0은 그대로 0 (검정색)
    # 1은 255로 변환됩니다 (흰색)
    src = src * 255    

    cnt, labels = cv2.connectedComponents(src)

    print('src:'), 
    print(src)
    print('labels:')
    print(labels)
    print('number of labels:', cnt)


def labeling_stats():
    src = cv2.imread('../data/img/result.png', cv2.IMREAD_GRAYSCALE)

    if src is None:
        print('Image load failed!')
        return

    # 엣지 검출과 같이 쓴다. 바이너리, 오츠
    _, src_bin = cv2.threshold(src, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)

    cnt, labels, stats, centroids = cv2.connectedComponentsWithStats(src_bin)

    dst = cv2.cvtColor(src, cv2.COLOR_GRAY2BGR)

    for i in range(1, cnt):
        (x, y, w, h, area) = stats[i]

        if area < 20:
            continue

        pt1 = (x, y)
        pt2 = (x + w, y + h)
        cv2.rectangle(dst, pt1, pt2, (0, 255, 255))

    cv2.imshow('src', src)
    cv2.imshow('dst', dst)

    cv2.waitKey()
    cv2.destroyAllWindows()


if __name__ == "__main__":
    sobel_edge()
    labeling_basic()
    labeling_stats()

src:
[[  0   0 255 255   0   0   0   0]
 [255 255 255 255   0   0 255   0]
 [255 255 255 255   0   0   0   0]
 [  0   0   0   0   0 255 255   0]
 [  0   0   0 255 255 255 255   0]
 [  0   0   0 255   0   0 255   0]
 [  0   0 255 255 255 255 255   0]
 [  0   0   0   0   0   0   0   0]]
labels:
[[0 0 1 1 0 0 0 0]
 [1 1 1 1 0 0 2 0]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 0 3 3 0]
 [0 0 0 3 3 3 3 0]
 [0 0 0 3 0 0 3 0]
 [0 0 3 3 3 3 3 0]
 [0 0 0 0 0 0 0 0]]
number of labels: 4


In [1]:
import numpy as np
import cv2
import random


def contours_basic():
    src = cv2.imread('../data/img/result.png', cv2.IMREAD_GRAYSCALE)

    if src is None:
        print('Image load failed!')
        return

    # contours, _ = cv2.findContours(src, cv2.RETR_LIST, cv2.CHAIN_APPROX_NONE)
    contours, _ = cv2.findContours(src, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

    dst = cv2.cvtColor(src, cv2.COLOR_GRAY2BGR)

    for i in range(len(contours)):
        c = (random.randint(0, 255), random.randint(0, 255), random.randint(0, 255))
        cv2.drawContours(dst, contours, i, c, 2)

    cv2.imshow('src', src)
    cv2.imshow('dst', dst)

    cv2.waitKey()
    cv2.destroyAllWindows()


def contours_hier():
    src = cv2.imread('../data/img/result.png', cv2.IMREAD_GRAYSCALE)

    if src is None:
        print('Image load failed!')
        return

    contours, hierarchy = cv2.findContours(src, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_SIMPLE)

    dst = cv2.cvtColor(src, cv2.COLOR_GRAY2BGR)

    idx = 0
    while idx >= 0:
        c = (random.randint(0, 255), random.randint(0, 255), random.randint(0, 255))
        cv2.drawContours(dst, contours, idx, c, -1, cv2.LINE_8, hierarchy)
        idx = hierarchy[0, idx, 0]

    cv2.imshow('src', src)
    cv2.imshow('dst', dst)

    cv2.waitKey()
    cv2.destroyAllWindows()


if __name__ == "__main__":
    contours_basic()
    contours_hier()


In [3]:
import numpy as np
import cv2
import math


def setLabel(img, pts, label):
    (x, y, w, h) = cv2.boundingRect(pts)
    pt1 = (x, y)
    pt2 = (x + w, y + h)
    cv2.rectangle(img, pt1, pt2, (0, 0, 255), 1)
    cv2.putText(img, label, pt1, cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 255))


def main():
    img = cv2.imread('../data/img/coins.png', cv2.IMREAD_COLOR)

    if img is None:
        print('Image load failed!')
        return

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    _, img_bin = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)
    contours, _ = cv2.findContours(img_bin, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

    for pts in contours:
        if cv2.contourArea(pts) < 400:
            continue

        approx = cv2.approxPolyDP(pts, cv2.arcLength(pts, True)*0.02, True)

        vtc = len(approx)

        if vtc == 3:
            setLabel(img, pts, 'TRI')
        elif vtc == 4:
            setLabel(img, pts, 'RECT')
        else:
            lenth = cv2.arcLength(pts, True)
            area = cv2.contourArea(pts)
            ratio = 4. * math.pi * area / (lenth * lenth)

            if ratio > 0.85:
                setLabel(img, pts, 'CIR')

    cv2.imshow('img', img)
    cv2.waitKey()
    cv2.destroyAllWindows()


if __name__ == '__main__':
    main()


In [4]:
import cv2
import numpy as np

# 이미지 읽어서 그레이스케일 변환, 바이너리 스케일 변환
img = cv2.imread("../data/img/coins.png")
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret, th = cv2.threshold(imgray, 127,255,cv2.THRESH_BINARY_INV)
# 컨튜어 찾기
contours, hr = cv2.findContours(th, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)[-2:]
contr = contours[0]
print(type(contr), contr.shape, contr.dtype)
# 감싸는 사각형 표시(검정색)
x,y,w,h = cv2.boundingRect(contr)
cv2.rectangle(img, (x,y), (x+w, y+h), (0,0,0), 3)
# 최소한의 사각형 표시(초록색)
rect = cv2.minAreaRect(contr)
box = cv2.boxPoints(rect)   # 중심점과 각도를 4개의 꼭지점 좌표로 변환
box = np.int0(box)          # 정수로 변환
cv2.drawContours(img, [box], -1, (0,255,0), 3)
# 최소한의 원 표시(파랑색)
(x,y), radius = cv2.minEnclosingCircle(contr)
cv2.circle(img, (int(x), int(y)), int(radius), (255,0,0), 2)
# 최소한의 삼각형 표시(분홍색)
ret, tri = cv2.minEnclosingTriangle(np.float32(contr))
cv2.polylines(img, [np.int32(tri)], True, (255,0,255), 2)
# 최소한의 타원 표시(노랑색)
ellipse = cv2.fitEllipse(contr)
cv2.ellipse(img, ellipse, (0,255,255), 3)
# 중심점 통과하는 직선 표시(빨강색)
vx,vy,x,y = cv2.fitLine(contr, cv2.DIST_L2,0,0.01,0.01)
cols,rows = img.shape[:2]
cv2.line(img, (0, int(0-x*(vy/vx) + y)), (cols-1, int((cols-x)*(vy/vx) + y)), (0,0,255),2)
# 결과 출력
cv2.imshow('Bound Fit shapes', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

<class 'numpy.ndarray'> (7, 1, 2) int32


C:\Users\shjung\AppData\Local\Temp\ipykernel_12488\3733196097.py:18: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  box = np.int0(box)          # 정수로 변환


In [6]:
import cv2
import numpy as np

def process_image():
    img = cv2.imread('../data/img/bbb.png')  # Replace with your image path

    if img is None:
        print('Image load failed!')
        return

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    _, binary = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)
    contours, _ = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    for contr in contours:
        if len(contr) >= 5:  # Ensure there are at least 5 points
            # Fit an ellipse
            ellipse = cv2.fitEllipse(contr)
            cv2.ellipse(img, ellipse, (0, 255, 255), 3)
        else:
            print(f"Contour with {len(contr)} points is too small to fit an ellipse.")

    cv2.imshow('Result', img)
    cv2.waitKey()
    cv2.destroyAllWindows()

if __name__ == '__main__':
    process_image()


Contour with 1 points is too small to fit an ellipse.
Contour with 1 points is too small to fit an ellipse.
Contour with 1 points is too small to fit an ellipse.
Contour with 4 points is too small to fit an ellipse.
Contour with 1 points is too small to fit an ellipse.
Contour with 2 points is too small to fit an ellipse.
Contour with 1 points is too small to fit an ellipse.
Contour with 1 points is too small to fit an ellipse.
Contour with 4 points is too small to fit an ellipse.
Contour with 1 points is too small to fit an ellipse.
Contour with 1 points is too small to fit an ellipse.
Contour with 2 points is too small to fit an ellipse.
Contour with 1 points is too small to fit an ellipse.
Contour with 4 points is too small to fit an ellipse.
Contour with 1 points is too small to fit an ellipse.
Contour with 1 points is too small to fit an ellipse.
Contour with 1 points is too small to fit an ellipse.
Contour with 1 points is too small to fit an ellipse.
Contour with 1 points is too

In [8]:
import cv2
import numpy as np

def process_image():
    img = cv2.imread('../data/img/fff.png')  # Replace with your image path

    if img is None:
        print('Image load failed!')
        return

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    _, binary = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)    
    contours, _ = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    for contr in contours:
        if len(contr) >= 5:  # Ensure there are at least 5 points
            try:
                # Fit an ellipse
                ellipse = cv2.fitEllipse(contr)

                # Check if the ellipse has valid dimensions
                if ellipse[1][0] > 0 and ellipse[1][1] > 0:
                    cv2.ellipse(img, ellipse, (0, 255, 255), 3)
                else:
                    print(f"Invalid ellipse dimensions: {ellipse[1]}")
            except cv2.error as e:
                print(f"OpenCV error: {e}")
        else:
            print(f"Contour with {len(contr)} points is too small to fit an ellipse.")

    cv2.imshow('Result', img)
    cv2.waitKey()
    cv2.destroyAllWindows()

if __name__ == '__main__':
    process_image()


Contour with 2 points is too small to fit an ellipse.
Contour with 1 points is too small to fit an ellipse.
Contour with 4 points is too small to fit an ellipse.
Contour with 1 points is too small to fit an ellipse.
Contour with 1 points is too small to fit an ellipse.
Contour with 2 points is too small to fit an ellipse.
Contour with 1 points is too small to fit an ellipse.
Contour with 2 points is too small to fit an ellipse.
Contour with 2 points is too small to fit an ellipse.
Contour with 1 points is too small to fit an ellipse.
Contour with 1 points is too small to fit an ellipse.
Contour with 2 points is too small to fit an ellipse.
Contour with 1 points is too small to fit an ellipse.
Contour with 2 points is too small to fit an ellipse.
Contour with 2 points is too small to fit an ellipse.
Contour with 1 points is too small to fit an ellipse.
Contour with 2 points is too small to fit an ellipse.
Contour with 2 points is too small to fit an ellipse.
Invalid ellipse dimensions: 

In [9]:
import cv2
import numpy as np

img = cv2.imread('../data/img/eee.png')

# 구조화 요소 커널, 사각형 (3x3) 생성 ---①
k = cv2.getStructuringElement(cv2.MORPH_RECT, (3,3))
# 팽창 연산 적용 ---②
dst = cv2.dilate(img, k)

# 결과 출력
merged = np.hstack((img, dst))
cv2.imshow('Dilation', merged)
cv2.waitKey(0)
cv2.destroyAllWindows()


## 필요

In [11]:
import cv2
import numpy as np

img = cv2.imread('../data/img/pcb-1.png')
img2 = cv2.imread('../data/img/pcb-2.png')

# 구조화 요소 커널, 사각형 (5x5) 생성 ---①
k = cv2.getStructuringElement(cv2.MORPH_RECT, (9,9))
# 탑햇 연산 적용 ---②
tophat = cv2.morphologyEx(img, cv2.MORPH_TOPHAT, k)
# 블랫햇 연산 적용 ---③
blackhat = cv2.morphologyEx(img, cv2.MORPH_BLACKHAT, k)


# 구조화 요소 커널, 사각형 (5x5) 생성 ---①
k = cv2.getStructuringElement(cv2.MORPH_RECT, (9,9))
# 탑햇 연산 적용 ---②
tophat2 = cv2.morphologyEx(img2, cv2.MORPH_TOPHAT, k)
# 블랫햇 연산 적용 ---③
blackhat2 = cv2.morphologyEx(img2, cv2.MORPH_BLACKHAT, k)

# 결과 출력
# merged = np.hstack((img, tophat, blackhat))
merged = np.hstack((blackhat, blackhat2))
cv2.imshow('tophat blackhat', merged)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 불량찾기

In [17]:
import sys
import numpy as np
import cv2


img = cv2.imread('../data/img/pcb-2.png', cv2.IMREAD_COLOR)
templ = cv2.imread('../data/img/cropped.jpg', cv2.IMREAD_COLOR)

if img is None or templ is None:
    print('Image load failed!')
    sys.exit()

img = img + (50, 50, 50)

noise = np.zeros(img.shape, np.int32)
cv2.randn(noise, 0, 10)
img = cv2.add(img, noise, dtype=cv2.CV_8UC3)

res = cv2.matchTemplate(img, templ, cv2.TM_CCOEFF_NORMED)
res_norm = cv2.normalize(res, None, 0, 255, cv2.NORM_MINMAX, cv2.CV_8U)

_, maxv, _, maxloc = cv2.minMaxLoc(res)
print('maxv:', maxv)

(th, tw) = templ.shape[:2]
cv2.rectangle(img, maxloc, (maxloc[0] + tw, maxloc[1] + th), (0, 0, 255), 2)

cv2.imshow('templ', templ)
cv2.imshow('res_norm', res_norm)
cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()


maxv: 0.38306790590286255


In [13]:
import sys
import numpy as np
import cv2


img = cv2.imread('../data/img/coin3.jpg', cv2.IMREAD_COLOR)
templ = cv2.imread('../data/img/coin3_cropped.jpg', cv2.IMREAD_COLOR)

if img is None or templ is None:
    print('Image load failed!')
    sys.exit()

# uint8
print(img.dtype) 

img = img + (50, 50, 50)

# int32
print(img.dtype)

noise = np.zeros(img.shape, np.int32)
cv2.randn(noise, 0, 10)
img = cv2.add(img, noise, dtype=cv2.CV_8UC3)

res = cv2.matchTemplate(img, templ, cv2.TM_CCOEFF_NORMED)
res_norm = cv2.normalize(res, None, 0, 255, cv2.NORM_MINMAX, cv2.CV_8U)
_, maxv, _, maxloc = cv2.minMaxLoc(res)
print('maxv:', maxv)

(th, tw) = templ.shape[:2]
cv2.rectangle(img, maxloc, (maxloc[0] + tw, maxloc[1] + th), (0, 0, 255), 2)

cv2.imshow('templ', templ)
cv2.imshow('res_norm', res_norm)
cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

Image load failed!


SystemExit: 

c:\anaconda3\envs\cv2\lib\site-packages\IPython\core\interactiveshell.py:3516: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [14]:
import numpy as np
import cv2


def detect_face():
    src = cv2.imread('../data/img/eee.png')

    if src is None:
        print('Image load failed!')
        return

    classifier = cv2.CascadeClassifier('./haarcascade_frontalface_default.xml')

    if classifier.empty():
        print('XML load failed!')
        return

    faces = classifier.detectMultiScale(src)

    for (x, y, w, h) in faces:
        cv2.rectangle(src, (x, y), (x + w, y + h), (255, 0, 255), 2)

    cv2.imshow('src', src)
    cv2.waitKey()
    cv2.destroyAllWindows()


def detect_eyes():
    src = cv2.imread('../data/img/eee.png')

    if src is None:
        print('Image load failed!')
        return

    face_classifier = cv2.CascadeClassifier('./haarcascade_frontalface_default.xml')
    eye_classifier = cv2.CascadeClassifier('./haarcascade_eye.xml')

    if face_classifier.empty() or eye_classifier.empty():
        print('XML load failed!')
        return

    faces = face_classifier.detectMultiScale(src)

    for (x1, y1, w1, h1) in faces:
        cv2.rectangle(src, (x1, y1), (x1 + w1, y1 + h1), (255, 0, 255), 2)

        faceROI = src[y1:y1 + h1, x1:x1 + w1]
        eyes = eye_classifier.detectMultiScale(faceROI)

        for (x2, y2, w2, h2) in eyes:
            center = (int(x2 + w2 / 2), int(y2 + h2 / 2))
            cv2.circle(faceROI, center, int(w2 / 2), (255, 0, 0), 2, cv2.LINE_AA)

    cv2.imshow('src', src)
    cv2.waitKey()
    cv2.destroyAllWindows()


if __name__ == '__main__':
    detect_face()
    detect_eyes()


In [13]:
import sys
import numpy as np
import cv2
import random


cap = cv2.VideoCapture('../data/img/streets.mp4')

if not cap.isOpened():
    print('Video open failed!')
    sys.exit()

hog = cv2.HOGDescriptor()
hog.setSVMDetector(cv2.HOGDescriptor_getDefaultPeopleDetector())

while True:
    ret, frame = cap.read()

    if not ret:
        break

    detected, _ = hog.detectMultiScale(frame)

    for (x, y, w, h) in detected:
        c = (random.randint(0, 255), random.randint(0, 255), random.randint(0, 255))
        cv2.rectangle(frame, (x, y), (x + w, y + h), c, 3)

    cv2.imshow('frame', frame)
    if cv2.waitKey(10) == 27:
        break

cv2.destroyAllWindows()


In [ ]:
import sys
import numpy as np
import cv2


cap = cv2.VideoCapture(0)

if not cap.isOpened():
    print('Video open failed!')
    sys.exit()

detector = cv2.QRCodeDetector()

while True:
    ret, frame = cap.read()

    if not ret:
        print('Frame load failed!')
        break

    info, points, _ = detector.detectAndDecode(frame)

    if points is not None:
        points = np.array(points, dtype=np.int32).reshape(4, 2)
        cv2.polylines(frame, [points], True, (0, 0, 255), 2)

    if len(info) > 0:
        cv2.putText(frame, info, (10, 30), cv2.FONT_HERSHEY_DUPLEX, 1, (0, 0, 255), lineType=cv2.LINE_AA)

    cv2.imshow('frame', frame)
    if cv2.waitKey(1) == 27:
        break

cv2.destroyAllWindows()


In [16]:
import cv2 as cv 

img=cv.imread('../data/img/coins.png')
gray=cv.cvtColor(img,cv.COLOR_BGR2GRAY)

apples=cv.HoughCircles(gray,cv.HOUGH_GRADIENT,1,200,param1=150,param2=20,minRadius=50,maxRadius=120)

for i in apples[0]: 
    cv.circle(img,(int(i[0]),int(i[1])),int(i[2]),(255,0,0),2)

cv.imshow('Apple detection',img)  

cv.waitKey()
cv.destroyAllWindows()

In [ ]:
import cv2 as cv
import numpy as np
import time

img1=cv.imread('mot_color70.jpg')[190:350,440:560] # 버스를 크롭하여 모델 영상으로 사용
gray1=cv.cvtColor(img1,cv.COLOR_BGR2GRAY)
img2=cv.imread('mot_color83.jpg')			     # 장면 영상
gray2=cv.cvtColor(img2,cv.COLOR_BGR2GRAY)

sift=cv.SIFT_create()
kp1,des1=sift.detectAndCompute(gray1,None)
kp2,des2=sift.detectAndCompute(gray2,None)
print('특징점 개수:',len(kp1),len(kp2)) 

start=time.time()
flann_matcher=cv.DescriptorMatcher_create(cv.DescriptorMatcher_FLANNBASED)
knn_match=flann_matcher.knnMatch(des1,des2,2)

T=0.7
good_match=[]
for nearest1,nearest2 in knn_match:
    if (nearest1.distance/nearest2.distance)<T:
        good_match.append(nearest1)
print('매칭에 걸린 시간:',time.time()-start) 

img_match=np.empty((max(img1.shape[0],img2.shape[0]),img1.shape[1]+img2.shape[1],3),dtype=np.uint8)
cv.drawMatches(img1,kp1,img2,kp2,good_match,img_match,flags=cv.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)

cv.imshow('Good Matches', img_match)

k=cv.waitKey()
cv.destroyAllWindows()